# Generated by Django 6.0 on 2025-12-17 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentinfo',
            old_name='student_class',
            new_name='class_name',
        ),
    ]
