# Generated by Django 6.0 on 2025-12-18 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_rename_student_class_studentinfo_class_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='fees',
            field=models.CharField(default='0', max_length=4),
        ),
    ]
