# Generated by Django 6.0 on 2026-01-06 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='fees',
            field=models.IntegerField(default=0),
        ),
    ]
